/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Transaction = IDL.Record({
  'id' : IDL.Text,
  'transactionType' : IDL.Text,
  'relatedLoanId' : IDL.Opt(IDL.Text),
  'date' : IDL.Int,
  'memberPrincipal' : IDL.Principal,
  'description' : IDL.Text,
  'groupId' : IDL.Text,
  'amount' : IDL.Float64,
});
export const Contribution = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'month' : IDL.Nat,
  'memberPrincipal' : IDL.Principal,
  'penaltyAmount' : IDL.Float64,
  'year' : IDL.Nat,
  'paidDate' : IDL.Opt(IDL.Int),
  'groupId' : IDL.Text,
  'amount' : IDL.Float64,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Loan = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'memberPrincipal' : IDL.Principal,
  'groupId' : IDL.Text,
  'outstandingBalance' : IDL.Float64,
  'interestRatePercent' : IDL.Float64,
  'principalAmount' : IDL.Float64,
  'startDate' : IDL.Int,
});
export const Group = IDL.Record({
  'id' : IDL.Text,
  'penaltyRatePercent' : IDL.Float64,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'createdBy' : IDL.Principal,
  'description' : IDL.Text,
  'interestRatePercent' : IDL.Float64,
  'groupCode' : IDL.Text,
  'monthlyContribution' : IDL.Float64,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});
export const GroupSummary = IDL.Record({
  'memberCount' : IDL.Nat,
  'totalFund' : IDL.Float64,
  'totalLoansOutstanding' : IDL.Float64,
  'totalPenalties' : IDL.Float64,
  'activeLoans' : IDL.Nat,
  'monthlyInterestEarned' : IDL.Float64,
});
export const GroupMembership = IDL.Record({
  'memberPrincipal' : IDL.Principal,
  'joinedAt' : IDL.Int,
  'isActive' : IDL.Bool,
  'memberEmail' : IDL.Text,
  'groupId' : IDL.Text,
  'memberName' : IDL.Text,
  'memberPhone' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'adjustRecord' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Float64, IDL.Text],
      [Transaction],
      [],
    ),
  'applyPenalty' : IDL.Func(
      [IDL.Text, IDL.Principal, IDL.Nat, IDL.Nat, IDL.Float64],
      [Contribution],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'closeLoan' : IDL.Func([IDL.Text, IDL.Text], [Loan], []),
  'createGroup' : IDL.Func([IDL.Text, IDL.Text], [Group], []),
  'createLoan' : IDL.Func([IDL.Text, IDL.Principal, IDL.Float64], [Loan], []),
  'deleteGroup' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'getAllTransactions' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Transaction)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getGroup' : IDL.Func([IDL.Text], [IDL.Opt(Group)], ['query']),
  'getGroupSummary' : IDL.Func([IDL.Text], [GroupSummary], ['query']),
  'getMyContributions' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Contribution)],
      ['query'],
    ),
  'getMyGroupProfile' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(GroupMembership)],
      ['query'],
    ),
  'getMyLoans' : IDL.Func([IDL.Text], [IDL.Vec(Loan)], ['query']),
  'getMyOutstandingBalance' : IDL.Func([IDL.Text], [IDL.Float64], ['query']),
  'getMyTransactions' : IDL.Func([IDL.Text], [IDL.Vec(Transaction)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'joinGroup' : IDL.Func([IDL.Text], [Group], []),
  'leaveGroup' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'listGroupMembers' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(GroupMembership)],
      ['query'],
    ),
  'listLoans' : IDL.Func([IDL.Text], [IDL.Vec(Loan)], ['query']),
  'listMyGroups' : IDL.Func([], [IDL.Vec(Group)], ['query']),
  'payContribution' : IDL.Func(
      [IDL.Text, IDL.Float64, IDL.Nat, IDL.Nat],
      [Contribution],
      [],
    ),
  'payLoanInterest' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Float64],
      [Transaction],
      [],
    ),
  'recordContribution' : IDL.Func(
      [IDL.Text, IDL.Principal, IDL.Float64, IDL.Nat, IDL.Nat],
      [Contribution],
      [],
    ),
  'removeMember' : IDL.Func([IDL.Text, IDL.Principal], [IDL.Bool], []),
  'repayPrincipal' : IDL.Func([IDL.Text, IDL.Text, IDL.Float64], [Loan], []),
  'runMonthlyInterestCalculation' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat],
      [IDL.Vec(Transaction)],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateGroupSettings' : IDL.Func(
      [IDL.Text, IDL.Float64, IDL.Float64, IDL.Float64],
      [Group],
      [],
    ),
  'updateMemberStatus' : IDL.Func(
      [IDL.Text, IDL.Principal, IDL.Bool],
      [GroupMembership],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Transaction = IDL.Record({
    'id' : IDL.Text,
    'transactionType' : IDL.Text,
    'relatedLoanId' : IDL.Opt(IDL.Text),
    'date' : IDL.Int,
    'memberPrincipal' : IDL.Principal,
    'description' : IDL.Text,
    'groupId' : IDL.Text,
    'amount' : IDL.Float64,
  });
  const Contribution = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'month' : IDL.Nat,
    'memberPrincipal' : IDL.Principal,
    'penaltyAmount' : IDL.Float64,
    'year' : IDL.Nat,
    'paidDate' : IDL.Opt(IDL.Int),
    'groupId' : IDL.Text,
    'amount' : IDL.Float64,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Loan = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'memberPrincipal' : IDL.Principal,
    'groupId' : IDL.Text,
    'outstandingBalance' : IDL.Float64,
    'interestRatePercent' : IDL.Float64,
    'principalAmount' : IDL.Float64,
    'startDate' : IDL.Int,
  });
  const Group = IDL.Record({
    'id' : IDL.Text,
    'penaltyRatePercent' : IDL.Float64,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'createdBy' : IDL.Principal,
    'description' : IDL.Text,
    'interestRatePercent' : IDL.Float64,
    'groupCode' : IDL.Text,
    'monthlyContribution' : IDL.Float64,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  const GroupSummary = IDL.Record({
    'memberCount' : IDL.Nat,
    'totalFund' : IDL.Float64,
    'totalLoansOutstanding' : IDL.Float64,
    'totalPenalties' : IDL.Float64,
    'activeLoans' : IDL.Nat,
    'monthlyInterestEarned' : IDL.Float64,
  });
  const GroupMembership = IDL.Record({
    'memberPrincipal' : IDL.Principal,
    'joinedAt' : IDL.Int,
    'isActive' : IDL.Bool,
    'memberEmail' : IDL.Text,
    'groupId' : IDL.Text,
    'memberName' : IDL.Text,
    'memberPhone' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'adjustRecord' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Float64, IDL.Text],
        [Transaction],
        [],
      ),
    'applyPenalty' : IDL.Func(
        [IDL.Text, IDL.Principal, IDL.Nat, IDL.Nat, IDL.Float64],
        [Contribution],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'closeLoan' : IDL.Func([IDL.Text, IDL.Text], [Loan], []),
    'createGroup' : IDL.Func([IDL.Text, IDL.Text], [Group], []),
    'createLoan' : IDL.Func([IDL.Text, IDL.Principal, IDL.Float64], [Loan], []),
    'deleteGroup' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'getAllTransactions' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Transaction)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getGroup' : IDL.Func([IDL.Text], [IDL.Opt(Group)], ['query']),
    'getGroupSummary' : IDL.Func([IDL.Text], [GroupSummary], ['query']),
    'getMyContributions' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Contribution)],
        ['query'],
      ),
    'getMyGroupProfile' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(GroupMembership)],
        ['query'],
      ),
    'getMyLoans' : IDL.Func([IDL.Text], [IDL.Vec(Loan)], ['query']),
    'getMyOutstandingBalance' : IDL.Func([IDL.Text], [IDL.Float64], ['query']),
    'getMyTransactions' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Transaction)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'joinGroup' : IDL.Func([IDL.Text], [Group], []),
    'leaveGroup' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'listGroupMembers' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(GroupMembership)],
        ['query'],
      ),
    'listLoans' : IDL.Func([IDL.Text], [IDL.Vec(Loan)], ['query']),
    'listMyGroups' : IDL.Func([], [IDL.Vec(Group)], ['query']),
    'payContribution' : IDL.Func(
        [IDL.Text, IDL.Float64, IDL.Nat, IDL.Nat],
        [Contribution],
        [],
      ),
    'payLoanInterest' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Float64],
        [Transaction],
        [],
      ),
    'recordContribution' : IDL.Func(
        [IDL.Text, IDL.Principal, IDL.Float64, IDL.Nat, IDL.Nat],
        [Contribution],
        [],
      ),
    'removeMember' : IDL.Func([IDL.Text, IDL.Principal], [IDL.Bool], []),
    'repayPrincipal' : IDL.Func([IDL.Text, IDL.Text, IDL.Float64], [Loan], []),
    'runMonthlyInterestCalculation' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat],
        [IDL.Vec(Transaction)],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateGroupSettings' : IDL.Func(
        [IDL.Text, IDL.Float64, IDL.Float64, IDL.Float64],
        [Group],
        [],
      ),
    'updateMemberStatus' : IDL.Func(
        [IDL.Text, IDL.Principal, IDL.Bool],
        [GroupMembership],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };