/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Contribution {
  'id' : string,
  'status' : string,
  'memberId' : string,
  'month' : bigint,
  'penaltyAmount' : number,
  'year' : bigint,
  'paidDate' : [] | [bigint],
  'amount' : number,
}
export interface GroupSettings {
  'penaltyRatePercent' : number,
  'interestRatePercent' : number,
  'monthlyContribution' : number,
}
export interface GroupSummary {
  'memberCount' : bigint,
  'totalFund' : number,
  'totalLoansOutstanding' : number,
  'totalPenalties' : number,
  'activeLoans' : bigint,
  'monthlyInterestEarned' : number,
}
export interface Loan {
  'id' : string,
  'status' : string,
  'memberId' : string,
  'outstandingBalance' : number,
  'interestRatePercent' : number,
  'principalAmount' : number,
  'startDate' : bigint,
}
export interface Member {
  'id' : string,
  'principal' : Principal,
  'joinDate' : bigint,
  'name' : string,
  'role' : string,
  'isActive' : boolean,
  'email' : string,
  'phone' : string,
}
export interface Transaction {
  'id' : string,
  'memberId' : string,
  'transactionType' : string,
  'relatedLoanId' : [] | [string],
  'date' : bigint,
  'description' : string,
  'amount' : number,
}
export interface UserProfile {
  'name' : string,
  'email' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addMember' : ActorMethod<[string, string, string], Member>,
  'adjustRecord' : ActorMethod<[string, number, string], Transaction>,
  'applyPenalty' : ActorMethod<[string, bigint, bigint, number], Contribution>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'closeLoan' : ActorMethod<[string], Loan>,
  'createLoan' : ActorMethod<[string, number], Loan>,
  'deleteMember' : ActorMethod<[string], boolean>,
  'editMember' : ActorMethod<[string, string, string, string, boolean], Member>,
  'getAllTransactions' : ActorMethod<[], Array<Transaction>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getGroupSettings' : ActorMethod<[], GroupSettings>,
  'getGroupSummary' : ActorMethod<[], GroupSummary>,
  'getLoan' : ActorMethod<[string], [] | [Loan]>,
  'getMember' : ActorMethod<[string], [] | [Member]>,
  'getMemberTransactions' : ActorMethod<[string], Array<Transaction>>,
  'getMyContributions' : ActorMethod<[], Array<Contribution>>,
  'getMyLoans' : ActorMethod<[], Array<Loan>>,
  'getMyOutstandingBalance' : ActorMethod<[], number>,
  'getMyProfile' : ActorMethod<[], [] | [Member]>,
  'getMyTransactions' : ActorMethod<[], Array<Transaction>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listLoans' : ActorMethod<[], Array<Loan>>,
  'listMembers' : ActorMethod<[], Array<Member>>,
  'payContribution' : ActorMethod<[number, bigint, bigint], Contribution>,
  'payLoanInterest' : ActorMethod<[string, number], Transaction>,
  'recordContribution' : ActorMethod<
    [string, number, bigint, bigint],
    Contribution
  >,
  'repayPrincipal' : ActorMethod<[string, number], Loan>,
  'runMonthlyInterestCalculation' : ActorMethod<
    [bigint, bigint],
    Array<Transaction>
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateGroupSettings' : ActorMethod<[number, number, number], GroupSettings>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];