/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Member = IDL.Record({
  'id' : IDL.Text,
  'principal' : IDL.Principal,
  'joinDate' : IDL.Int,
  'name' : IDL.Text,
  'role' : IDL.Text,
  'isActive' : IDL.Bool,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});
export const Transaction = IDL.Record({
  'id' : IDL.Text,
  'memberId' : IDL.Text,
  'transactionType' : IDL.Text,
  'relatedLoanId' : IDL.Opt(IDL.Text),
  'date' : IDL.Int,
  'description' : IDL.Text,
  'amount' : IDL.Float64,
});
export const Contribution = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'memberId' : IDL.Text,
  'month' : IDL.Nat,
  'penaltyAmount' : IDL.Float64,
  'year' : IDL.Nat,
  'paidDate' : IDL.Opt(IDL.Int),
  'amount' : IDL.Float64,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Loan = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'memberId' : IDL.Text,
  'outstandingBalance' : IDL.Float64,
  'interestRatePercent' : IDL.Float64,
  'principalAmount' : IDL.Float64,
  'startDate' : IDL.Int,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});
export const GroupSettings = IDL.Record({
  'penaltyRatePercent' : IDL.Float64,
  'interestRatePercent' : IDL.Float64,
  'monthlyContribution' : IDL.Float64,
});
export const GroupSummary = IDL.Record({
  'memberCount' : IDL.Nat,
  'totalFund' : IDL.Float64,
  'totalLoansOutstanding' : IDL.Float64,
  'totalPenalties' : IDL.Float64,
  'activeLoans' : IDL.Nat,
  'monthlyInterestEarned' : IDL.Float64,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addMember' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [Member], []),
  'adjustRecord' : IDL.Func(
      [IDL.Text, IDL.Float64, IDL.Text],
      [Transaction],
      [],
    ),
  'applyPenalty' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat, IDL.Float64],
      [Contribution],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'closeLoan' : IDL.Func([IDL.Text], [Loan], []),
  'createLoan' : IDL.Func([IDL.Text, IDL.Float64], [Loan], []),
  'deleteMember' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'editMember' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
      [Member],
      [],
    ),
  'getAllTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getGroupSettings' : IDL.Func([], [GroupSettings], ['query']),
  'getGroupSummary' : IDL.Func([], [GroupSummary], ['query']),
  'getLoan' : IDL.Func([IDL.Text], [IDL.Opt(Loan)], ['query']),
  'getMember' : IDL.Func([IDL.Text], [IDL.Opt(Member)], ['query']),
  'getMemberTransactions' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Transaction)],
      ['query'],
    ),
  'getMyContributions' : IDL.Func([], [IDL.Vec(Contribution)], ['query']),
  'getMyLoans' : IDL.Func([], [IDL.Vec(Loan)], ['query']),
  'getMyOutstandingBalance' : IDL.Func([], [IDL.Float64], ['query']),
  'getMyProfile' : IDL.Func([], [IDL.Opt(Member)], ['query']),
  'getMyTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listLoans' : IDL.Func([], [IDL.Vec(Loan)], ['query']),
  'listMembers' : IDL.Func([], [IDL.Vec(Member)], ['query']),
  'payContribution' : IDL.Func(
      [IDL.Float64, IDL.Nat, IDL.Nat],
      [Contribution],
      [],
    ),
  'payLoanInterest' : IDL.Func([IDL.Text, IDL.Float64], [Transaction], []),
  'recordContribution' : IDL.Func(
      [IDL.Text, IDL.Float64, IDL.Nat, IDL.Nat],
      [Contribution],
      [],
    ),
  'repayPrincipal' : IDL.Func([IDL.Text, IDL.Float64], [Loan], []),
  'runMonthlyInterestCalculation' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(Transaction)],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateGroupSettings' : IDL.Func(
      [IDL.Float64, IDL.Float64, IDL.Float64],
      [GroupSettings],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Member = IDL.Record({
    'id' : IDL.Text,
    'principal' : IDL.Principal,
    'joinDate' : IDL.Int,
    'name' : IDL.Text,
    'role' : IDL.Text,
    'isActive' : IDL.Bool,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  const Transaction = IDL.Record({
    'id' : IDL.Text,
    'memberId' : IDL.Text,
    'transactionType' : IDL.Text,
    'relatedLoanId' : IDL.Opt(IDL.Text),
    'date' : IDL.Int,
    'description' : IDL.Text,
    'amount' : IDL.Float64,
  });
  const Contribution = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'memberId' : IDL.Text,
    'month' : IDL.Nat,
    'penaltyAmount' : IDL.Float64,
    'year' : IDL.Nat,
    'paidDate' : IDL.Opt(IDL.Int),
    'amount' : IDL.Float64,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Loan = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'memberId' : IDL.Text,
    'outstandingBalance' : IDL.Float64,
    'interestRatePercent' : IDL.Float64,
    'principalAmount' : IDL.Float64,
    'startDate' : IDL.Int,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  const GroupSettings = IDL.Record({
    'penaltyRatePercent' : IDL.Float64,
    'interestRatePercent' : IDL.Float64,
    'monthlyContribution' : IDL.Float64,
  });
  const GroupSummary = IDL.Record({
    'memberCount' : IDL.Nat,
    'totalFund' : IDL.Float64,
    'totalLoansOutstanding' : IDL.Float64,
    'totalPenalties' : IDL.Float64,
    'activeLoans' : IDL.Nat,
    'monthlyInterestEarned' : IDL.Float64,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addMember' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [Member], []),
    'adjustRecord' : IDL.Func(
        [IDL.Text, IDL.Float64, IDL.Text],
        [Transaction],
        [],
      ),
    'applyPenalty' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat, IDL.Float64],
        [Contribution],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'closeLoan' : IDL.Func([IDL.Text], [Loan], []),
    'createLoan' : IDL.Func([IDL.Text, IDL.Float64], [Loan], []),
    'deleteMember' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'editMember' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
        [Member],
        [],
      ),
    'getAllTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getGroupSettings' : IDL.Func([], [GroupSettings], ['query']),
    'getGroupSummary' : IDL.Func([], [GroupSummary], ['query']),
    'getLoan' : IDL.Func([IDL.Text], [IDL.Opt(Loan)], ['query']),
    'getMember' : IDL.Func([IDL.Text], [IDL.Opt(Member)], ['query']),
    'getMemberTransactions' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Transaction)],
        ['query'],
      ),
    'getMyContributions' : IDL.Func([], [IDL.Vec(Contribution)], ['query']),
    'getMyLoans' : IDL.Func([], [IDL.Vec(Loan)], ['query']),
    'getMyOutstandingBalance' : IDL.Func([], [IDL.Float64], ['query']),
    'getMyProfile' : IDL.Func([], [IDL.Opt(Member)], ['query']),
    'getMyTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listLoans' : IDL.Func([], [IDL.Vec(Loan)], ['query']),
    'listMembers' : IDL.Func([], [IDL.Vec(Member)], ['query']),
    'payContribution' : IDL.Func(
        [IDL.Float64, IDL.Nat, IDL.Nat],
        [Contribution],
        [],
      ),
    'payLoanInterest' : IDL.Func([IDL.Text, IDL.Float64], [Transaction], []),
    'recordContribution' : IDL.Func(
        [IDL.Text, IDL.Float64, IDL.Nat, IDL.Nat],
        [Contribution],
        [],
      ),
    'repayPrincipal' : IDL.Func([IDL.Text, IDL.Float64], [Loan], []),
    'runMonthlyInterestCalculation' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(Transaction)],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateGroupSettings' : IDL.Func(
        [IDL.Float64, IDL.Float64, IDL.Float64],
        [GroupSettings],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };