/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Contribution {
  'id' : string,
  'status' : string,
  'month' : bigint,
  'memberPrincipal' : Principal,
  'penaltyAmount' : number,
  'year' : bigint,
  'paidDate' : [] | [bigint],
  'groupId' : string,
  'amount' : number,
}
export interface Group {
  'id' : string,
  'penaltyRatePercent' : number,
  'name' : string,
  'createdAt' : bigint,
  'createdBy' : Principal,
  'description' : string,
  'interestRatePercent' : number,
  'groupCode' : string,
  'monthlyContribution' : number,
}
export interface GroupMembership {
  'memberPrincipal' : Principal,
  'joinedAt' : bigint,
  'isActive' : boolean,
  'memberEmail' : string,
  'groupId' : string,
  'memberName' : string,
  'memberPhone' : string,
}
export interface GroupSummary {
  'memberCount' : bigint,
  'totalFund' : number,
  'totalLoansOutstanding' : number,
  'totalPenalties' : number,
  'activeLoans' : bigint,
  'monthlyInterestEarned' : number,
}
export interface Loan {
  'id' : string,
  'status' : string,
  'memberPrincipal' : Principal,
  'groupId' : string,
  'outstandingBalance' : number,
  'interestRatePercent' : number,
  'principalAmount' : number,
  'startDate' : bigint,
}
export interface Transaction {
  'id' : string,
  'transactionType' : string,
  'relatedLoanId' : [] | [string],
  'date' : bigint,
  'memberPrincipal' : Principal,
  'description' : string,
  'groupId' : string,
  'amount' : number,
}
export interface UserProfile {
  'name' : string,
  'email' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'adjustRecord' : ActorMethod<[string, string, number, string], Transaction>,
  'applyPenalty' : ActorMethod<
    [string, Principal, bigint, bigint, number],
    Contribution
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'closeLoan' : ActorMethod<[string, string], Loan>,
  'createGroup' : ActorMethod<[string, string], Group>,
  'createLoan' : ActorMethod<[string, Principal, number], Loan>,
  'deleteGroup' : ActorMethod<[string], boolean>,
  'getAllTransactions' : ActorMethod<[string], Array<Transaction>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getGroup' : ActorMethod<[string], [] | [Group]>,
  'getGroupSummary' : ActorMethod<[string], GroupSummary>,
  'getMyContributions' : ActorMethod<[string], Array<Contribution>>,
  'getMyGroupProfile' : ActorMethod<[string], [] | [GroupMembership]>,
  'getMyLoans' : ActorMethod<[string], Array<Loan>>,
  'getMyOutstandingBalance' : ActorMethod<[string], number>,
  'getMyTransactions' : ActorMethod<[string], Array<Transaction>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'joinGroup' : ActorMethod<[string], Group>,
  'leaveGroup' : ActorMethod<[string], boolean>,
  'listGroupMembers' : ActorMethod<[string], Array<GroupMembership>>,
  'listLoans' : ActorMethod<[string], Array<Loan>>,
  'listMyGroups' : ActorMethod<[], Array<Group>>,
  'payContribution' : ActorMethod<
    [string, number, bigint, bigint],
    Contribution
  >,
  'payLoanInterest' : ActorMethod<[string, string, number], Transaction>,
  'recordContribution' : ActorMethod<
    [string, Principal, number, bigint, bigint],
    Contribution
  >,
  'removeMember' : ActorMethod<[string, Principal], boolean>,
  'repayPrincipal' : ActorMethod<[string, string, number], Loan>,
  'runMonthlyInterestCalculation' : ActorMethod<
    [string, bigint, bigint],
    Array<Transaction>
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateGroupSettings' : ActorMethod<[string, number, number, number], Group>,
  'updateMemberStatus' : ActorMethod<
    [string, Principal, boolean],
    GroupMembership
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];