/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface GroupSummary {
    memberCount: bigint;
    totalFund: number;
    totalLoansOutstanding: number;
    totalPenalties: number;
    activeLoans: bigint;
    monthlyInterestEarned: number;
}
export interface Member {
    id: string;
    principal: Principal;
    joinDate: bigint;
    name: string;
    role: string;
    isActive: boolean;
    email: string;
    phone: string;
}
export interface Loan {
    id: string;
    status: string;
    memberId: string;
    outstandingBalance: number;
    interestRatePercent: number;
    principalAmount: number;
    startDate: bigint;
}
export interface GroupSettings {
    penaltyRatePercent: number;
    interestRatePercent: number;
    monthlyContribution: number;
}
export interface Contribution {
    id: string;
    status: string;
    memberId: string;
    month: bigint;
    penaltyAmount: number;
    year: bigint;
    paidDate?: bigint;
    amount: number;
}
export interface UserProfile {
    name: string;
    email: string;
    phone: string;
}
export interface Transaction {
    id: string;
    memberId: string;
    transactionType: string;
    relatedLoanId?: string;
    date: bigint;
    description: string;
    amount: number;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addMember(name: string, email: string, phone: string): Promise<Member>;
    adjustRecord(transactionId: string, newAmount: number, description: string): Promise<Transaction>;
    applyPenalty(memberId: string, month: bigint, year: bigint, penaltyAmount: number): Promise<Contribution>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    closeLoan(loanId: string): Promise<Loan>;
    createLoan(memberId: string, principalAmount: number): Promise<Loan>;
    deleteMember(id: string): Promise<boolean>;
    editMember(id: string, name: string, email: string, phone: string, isActive: boolean): Promise<Member>;
    getAllTransactions(): Promise<Array<Transaction>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getGroupSettings(): Promise<GroupSettings>;
    getGroupSummary(): Promise<GroupSummary>;
    getLoan(id: string): Promise<Loan | null>;
    getMember(id: string): Promise<Member | null>;
    getMemberTransactions(memberId: string): Promise<Array<Transaction>>;
    getMyContributions(): Promise<Array<Contribution>>;
    getMyLoans(): Promise<Array<Loan>>;
    getMyOutstandingBalance(): Promise<number>;
    getMyProfile(): Promise<Member | null>;
    getMyTransactions(): Promise<Array<Transaction>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    listLoans(): Promise<Array<Loan>>;
    listMembers(): Promise<Array<Member>>;
    payContribution(amount: number, month: bigint, year: bigint): Promise<Contribution>;
    payLoanInterest(loanId: string, amount: number): Promise<Transaction>;
    recordContribution(memberId: string, amount: number, month: bigint, year: bigint): Promise<Contribution>;
    repayPrincipal(loanId: string, amount: number): Promise<Loan>;
    runMonthlyInterestCalculation(month: bigint, year: bigint): Promise<Array<Transaction>>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateGroupSettings(monthlyContribution: number, interestRatePercent: number, penaltyRatePercent: number): Promise<GroupSettings>;
}
import type { Contribution as _Contribution, Loan as _Loan, Member as _Member, Transaction as _Transaction, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addMember(arg0: string, arg1: string, arg2: string): Promise<Member> {
        if (this.processError) {
            try {
                const result = await this.actor.addMember(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMember(arg0, arg1, arg2);
            return result;
        }
    }
    async adjustRecord(arg0: string, arg1: number, arg2: string): Promise<Transaction> {
        if (this.processError) {
            try {
                const result = await this.actor.adjustRecord(arg0, arg1, arg2);
                return from_candid_Transaction_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adjustRecord(arg0, arg1, arg2);
            return from_candid_Transaction_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async applyPenalty(arg0: string, arg1: bigint, arg2: bigint, arg3: number): Promise<Contribution> {
        if (this.processError) {
            try {
                const result = await this.actor.applyPenalty(arg0, arg1, arg2, arg3);
                return from_candid_Contribution_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.applyPenalty(arg0, arg1, arg2, arg3);
            return from_candid_Contribution_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n7(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n7(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async closeLoan(arg0: string): Promise<Loan> {
        if (this.processError) {
            try {
                const result = await this.actor.closeLoan(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.closeLoan(arg0);
            return result;
        }
    }
    async createLoan(arg0: string, arg1: number): Promise<Loan> {
        if (this.processError) {
            try {
                const result = await this.actor.createLoan(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createLoan(arg0, arg1);
            return result;
        }
    }
    async deleteMember(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMember(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMember(arg0);
            return result;
        }
    }
    async editMember(arg0: string, arg1: string, arg2: string, arg3: string, arg4: boolean): Promise<Member> {
        if (this.processError) {
            try {
                const result = await this.actor.editMember(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.editMember(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async getAllTransactions(): Promise<Array<Transaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTransactions();
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTransactions();
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGroupSettings(): Promise<GroupSettings> {
        if (this.processError) {
            try {
                const result = await this.actor.getGroupSettings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGroupSettings();
            return result;
        }
    }
    async getGroupSummary(): Promise<GroupSummary> {
        if (this.processError) {
            try {
                const result = await this.actor.getGroupSummary();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGroupSummary();
            return result;
        }
    }
    async getLoan(arg0: string): Promise<Loan | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getLoan(arg0);
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLoan(arg0);
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMember(arg0: string): Promise<Member | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMember(arg0);
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMember(arg0);
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMemberTransactions(arg0: string): Promise<Array<Transaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMemberTransactions(arg0);
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMemberTransactions(arg0);
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyContributions(): Promise<Array<Contribution>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyContributions();
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyContributions();
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyLoans(): Promise<Array<Loan>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyLoans();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyLoans();
            return result;
        }
    }
    async getMyOutstandingBalance(): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyOutstandingBalance();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyOutstandingBalance();
            return result;
        }
    }
    async getMyProfile(): Promise<Member | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyProfile();
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyProfile();
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyTransactions(): Promise<Array<Transaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyTransactions();
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyTransactions();
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listLoans(): Promise<Array<Loan>> {
        if (this.processError) {
            try {
                const result = await this.actor.listLoans();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listLoans();
            return result;
        }
    }
    async listMembers(): Promise<Array<Member>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMembers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMembers();
            return result;
        }
    }
    async payContribution(arg0: number, arg1: bigint, arg2: bigint): Promise<Contribution> {
        if (this.processError) {
            try {
                const result = await this.actor.payContribution(arg0, arg1, arg2);
                return from_candid_Contribution_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.payContribution(arg0, arg1, arg2);
            return from_candid_Contribution_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async payLoanInterest(arg0: string, arg1: number): Promise<Transaction> {
        if (this.processError) {
            try {
                const result = await this.actor.payLoanInterest(arg0, arg1);
                return from_candid_Transaction_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.payLoanInterest(arg0, arg1);
            return from_candid_Transaction_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async recordContribution(arg0: string, arg1: number, arg2: bigint, arg3: bigint): Promise<Contribution> {
        if (this.processError) {
            try {
                const result = await this.actor.recordContribution(arg0, arg1, arg2, arg3);
                return from_candid_Contribution_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordContribution(arg0, arg1, arg2, arg3);
            return from_candid_Contribution_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async repayPrincipal(arg0: string, arg1: number): Promise<Loan> {
        if (this.processError) {
            try {
                const result = await this.actor.repayPrincipal(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.repayPrincipal(arg0, arg1);
            return result;
        }
    }
    async runMonthlyInterestCalculation(arg0: bigint, arg1: bigint): Promise<Array<Transaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.runMonthlyInterestCalculation(arg0, arg1);
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.runMonthlyInterestCalculation(arg0, arg1);
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async updateGroupSettings(arg0: number, arg1: number, arg2: number): Promise<GroupSettings> {
        if (this.processError) {
            try {
                const result = await this.actor.updateGroupSettings(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateGroupSettings(arg0, arg1, arg2);
            return result;
        }
    }
}
function from_candid_Contribution_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Contribution): Contribution {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_Transaction_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Transaction): Transaction {
    return from_candid_record_n2(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Loan]): Loan | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Member]): Member | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    memberId: string;
    transactionType: string;
    relatedLoanId: [] | [string];
    date: bigint;
    description: string;
    amount: number;
}): {
    id: string;
    memberId: string;
    transactionType: string;
    relatedLoanId?: string;
    date: bigint;
    description: string;
    amount: number;
} {
    return {
        id: value.id,
        memberId: value.memberId,
        transactionType: value.transactionType,
        relatedLoanId: record_opt_to_undefined(from_candid_opt_n3(_uploadFile, _downloadFile, value.relatedLoanId)),
        date: value.date,
        description: value.description,
        amount: value.amount
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: string;
    memberId: string;
    month: bigint;
    penaltyAmount: number;
    year: bigint;
    paidDate: [] | [bigint];
    amount: number;
}): {
    id: string;
    status: string;
    memberId: string;
    month: bigint;
    penaltyAmount: number;
    year: bigint;
    paidDate?: bigint;
    amount: number;
} {
    return {
        id: value.id,
        status: value.status,
        memberId: value.memberId,
        month: value.month,
        penaltyAmount: value.penaltyAmount,
        year: value.year,
        paidDate: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.paidDate)),
        amount: value.amount
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Contribution>): Array<Contribution> {
    return value.map((x)=>from_candid_Contribution_n4(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Transaction>): Array<Transaction> {
    return value.map((x)=>from_candid_Transaction_n1(_uploadFile, _downloadFile, x));
}
function to_candid_UserRole_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
