/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface GroupSummary {
    memberCount: bigint;
    totalFund: number;
    totalLoansOutstanding: number;
    totalPenalties: number;
    activeLoans: bigint;
    monthlyInterestEarned: number;
}
export interface GroupMembership {
    memberPrincipal: Principal;
    joinedAt: bigint;
    isActive: boolean;
    memberEmail: string;
    groupId: string;
    memberName: string;
    memberPhone: string;
}
export interface Loan {
    id: string;
    status: string;
    memberPrincipal: Principal;
    groupId: string;
    outstandingBalance: number;
    interestRatePercent: number;
    principalAmount: number;
    startDate: bigint;
}
export interface Group {
    id: string;
    penaltyRatePercent: number;
    name: string;
    createdAt: bigint;
    createdBy: Principal;
    description: string;
    interestRatePercent: number;
    groupCode: string;
    monthlyContribution: number;
}
export interface Contribution {
    id: string;
    status: string;
    month: bigint;
    memberPrincipal: Principal;
    penaltyAmount: number;
    year: bigint;
    paidDate?: bigint;
    groupId: string;
    amount: number;
}
export interface UserProfile {
    name: string;
    email: string;
    phone: string;
}
export interface Transaction {
    id: string;
    transactionType: string;
    relatedLoanId?: string;
    date: bigint;
    memberPrincipal: Principal;
    description: string;
    groupId: string;
    amount: number;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    adjustRecord(groupId: string, transactionId: string, newAmount: number, description: string): Promise<Transaction>;
    applyPenalty(groupId: string, memberPrincipal: Principal, month: bigint, year: bigint, penaltyAmount: number): Promise<Contribution>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    closeLoan(groupId: string, loanId: string): Promise<Loan>;
    createGroup(name: string, description: string): Promise<Group>;
    createLoan(groupId: string, memberPrincipal: Principal, principalAmount: number): Promise<Loan>;
    deleteGroup(groupId: string): Promise<boolean>;
    getAllTransactions(groupId: string): Promise<Array<Transaction>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getGroup(groupId: string): Promise<Group | null>;
    getGroupSummary(groupId: string): Promise<GroupSummary>;
    getMyContributions(groupId: string): Promise<Array<Contribution>>;
    getMyGroupProfile(groupId: string): Promise<GroupMembership | null>;
    getMyLoans(groupId: string): Promise<Array<Loan>>;
    getMyOutstandingBalance(groupId: string): Promise<number>;
    getMyTransactions(groupId: string): Promise<Array<Transaction>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    joinGroup(groupCode: string): Promise<Group>;
    leaveGroup(groupId: string): Promise<boolean>;
    listGroupMembers(groupId: string): Promise<Array<GroupMembership>>;
    listLoans(groupId: string): Promise<Array<Loan>>;
    listMyGroups(): Promise<Array<Group>>;
    payContribution(groupId: string, amount: number, month: bigint, year: bigint): Promise<Contribution>;
    payLoanInterest(groupId: string, loanId: string, amount: number): Promise<Transaction>;
    recordContribution(groupId: string, memberPrincipal: Principal, amount: number, month: bigint, year: bigint): Promise<Contribution>;
    removeMember(groupId: string, memberPrincipal: Principal): Promise<boolean>;
    repayPrincipal(groupId: string, loanId: string, amount: number): Promise<Loan>;
    runMonthlyInterestCalculation(groupId: string, month: bigint, year: bigint): Promise<Array<Transaction>>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateGroupSettings(groupId: string, monthlyContribution: number, interestRatePercent: number, penaltyRatePercent: number): Promise<Group>;
    updateMemberStatus(groupId: string, memberPrincipal: Principal, isActive: boolean): Promise<GroupMembership>;
}
import type { Contribution as _Contribution, Group as _Group, GroupMembership as _GroupMembership, Transaction as _Transaction, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async adjustRecord(arg0: string, arg1: string, arg2: number, arg3: string): Promise<Transaction> {
        if (this.processError) {
            try {
                const result = await this.actor.adjustRecord(arg0, arg1, arg2, arg3);
                return from_candid_Transaction_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adjustRecord(arg0, arg1, arg2, arg3);
            return from_candid_Transaction_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async applyPenalty(arg0: string, arg1: Principal, arg2: bigint, arg3: bigint, arg4: number): Promise<Contribution> {
        if (this.processError) {
            try {
                const result = await this.actor.applyPenalty(arg0, arg1, arg2, arg3, arg4);
                return from_candid_Contribution_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.applyPenalty(arg0, arg1, arg2, arg3, arg4);
            return from_candid_Contribution_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n7(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n7(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async closeLoan(arg0: string, arg1: string): Promise<Loan> {
        if (this.processError) {
            try {
                const result = await this.actor.closeLoan(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.closeLoan(arg0, arg1);
            return result;
        }
    }
    async createGroup(arg0: string, arg1: string): Promise<Group> {
        if (this.processError) {
            try {
                const result = await this.actor.createGroup(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createGroup(arg0, arg1);
            return result;
        }
    }
    async createLoan(arg0: string, arg1: Principal, arg2: number): Promise<Loan> {
        if (this.processError) {
            try {
                const result = await this.actor.createLoan(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createLoan(arg0, arg1, arg2);
            return result;
        }
    }
    async deleteGroup(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteGroup(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteGroup(arg0);
            return result;
        }
    }
    async getAllTransactions(arg0: string): Promise<Array<Transaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTransactions(arg0);
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTransactions(arg0);
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGroup(arg0: string): Promise<Group | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getGroup(arg0);
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGroup(arg0);
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGroupSummary(arg0: string): Promise<GroupSummary> {
        if (this.processError) {
            try {
                const result = await this.actor.getGroupSummary(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGroupSummary(arg0);
            return result;
        }
    }
    async getMyContributions(arg0: string): Promise<Array<Contribution>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyContributions(arg0);
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyContributions(arg0);
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyGroupProfile(arg0: string): Promise<GroupMembership | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyGroupProfile(arg0);
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyGroupProfile(arg0);
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyLoans(arg0: string): Promise<Array<Loan>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyLoans(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyLoans(arg0);
            return result;
        }
    }
    async getMyOutstandingBalance(arg0: string): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyOutstandingBalance(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyOutstandingBalance(arg0);
            return result;
        }
    }
    async getMyTransactions(arg0: string): Promise<Array<Transaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyTransactions(arg0);
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyTransactions(arg0);
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async joinGroup(arg0: string): Promise<Group> {
        if (this.processError) {
            try {
                const result = await this.actor.joinGroup(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.joinGroup(arg0);
            return result;
        }
    }
    async leaveGroup(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.leaveGroup(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.leaveGroup(arg0);
            return result;
        }
    }
    async listGroupMembers(arg0: string): Promise<Array<GroupMembership>> {
        if (this.processError) {
            try {
                const result = await this.actor.listGroupMembers(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listGroupMembers(arg0);
            return result;
        }
    }
    async listLoans(arg0: string): Promise<Array<Loan>> {
        if (this.processError) {
            try {
                const result = await this.actor.listLoans(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listLoans(arg0);
            return result;
        }
    }
    async listMyGroups(): Promise<Array<Group>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMyGroups();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMyGroups();
            return result;
        }
    }
    async payContribution(arg0: string, arg1: number, arg2: bigint, arg3: bigint): Promise<Contribution> {
        if (this.processError) {
            try {
                const result = await this.actor.payContribution(arg0, arg1, arg2, arg3);
                return from_candid_Contribution_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.payContribution(arg0, arg1, arg2, arg3);
            return from_candid_Contribution_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async payLoanInterest(arg0: string, arg1: string, arg2: number): Promise<Transaction> {
        if (this.processError) {
            try {
                const result = await this.actor.payLoanInterest(arg0, arg1, arg2);
                return from_candid_Transaction_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.payLoanInterest(arg0, arg1, arg2);
            return from_candid_Transaction_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async recordContribution(arg0: string, arg1: Principal, arg2: number, arg3: bigint, arg4: bigint): Promise<Contribution> {
        if (this.processError) {
            try {
                const result = await this.actor.recordContribution(arg0, arg1, arg2, arg3, arg4);
                return from_candid_Contribution_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordContribution(arg0, arg1, arg2, arg3, arg4);
            return from_candid_Contribution_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async removeMember(arg0: string, arg1: Principal): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.removeMember(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeMember(arg0, arg1);
            return result;
        }
    }
    async repayPrincipal(arg0: string, arg1: string, arg2: number): Promise<Loan> {
        if (this.processError) {
            try {
                const result = await this.actor.repayPrincipal(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.repayPrincipal(arg0, arg1, arg2);
            return result;
        }
    }
    async runMonthlyInterestCalculation(arg0: string, arg1: bigint, arg2: bigint): Promise<Array<Transaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.runMonthlyInterestCalculation(arg0, arg1, arg2);
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.runMonthlyInterestCalculation(arg0, arg1, arg2);
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async updateGroupSettings(arg0: string, arg1: number, arg2: number, arg3: number): Promise<Group> {
        if (this.processError) {
            try {
                const result = await this.actor.updateGroupSettings(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateGroupSettings(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async updateMemberStatus(arg0: string, arg1: Principal, arg2: boolean): Promise<GroupMembership> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMemberStatus(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMemberStatus(arg0, arg1, arg2);
            return result;
        }
    }
}
function from_candid_Contribution_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Contribution): Contribution {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_Transaction_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Transaction): Transaction {
    return from_candid_record_n2(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Group]): Group | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_GroupMembership]): GroupMembership | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    transactionType: string;
    relatedLoanId: [] | [string];
    date: bigint;
    memberPrincipal: Principal;
    description: string;
    groupId: string;
    amount: number;
}): {
    id: string;
    transactionType: string;
    relatedLoanId?: string;
    date: bigint;
    memberPrincipal: Principal;
    description: string;
    groupId: string;
    amount: number;
} {
    return {
        id: value.id,
        transactionType: value.transactionType,
        relatedLoanId: record_opt_to_undefined(from_candid_opt_n3(_uploadFile, _downloadFile, value.relatedLoanId)),
        date: value.date,
        memberPrincipal: value.memberPrincipal,
        description: value.description,
        groupId: value.groupId,
        amount: value.amount
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: string;
    month: bigint;
    memberPrincipal: Principal;
    penaltyAmount: number;
    year: bigint;
    paidDate: [] | [bigint];
    groupId: string;
    amount: number;
}): {
    id: string;
    status: string;
    month: bigint;
    memberPrincipal: Principal;
    penaltyAmount: number;
    year: bigint;
    paidDate?: bigint;
    groupId: string;
    amount: number;
} {
    return {
        id: value.id,
        status: value.status,
        month: value.month,
        memberPrincipal: value.memberPrincipal,
        penaltyAmount: value.penaltyAmount,
        year: value.year,
        paidDate: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.paidDate)),
        groupId: value.groupId,
        amount: value.amount
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Contribution>): Array<Contribution> {
    return value.map((x)=>from_candid_Contribution_n4(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Transaction>): Array<Transaction> {
    return value.map((x)=>from_candid_Transaction_n1(_uploadFile, _downloadFile, x));
}
function to_candid_UserRole_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
